http://localhost:3100/users
###
http://localhost:3100/users/61953d517d480cd4282aab1b
###
POST http://localhost:3100/users/reset
###
POST http://localhost:3100/users/login
Content-Type: application/json

    { 
        "handle": "@vp",
        "password": "Her"
    }



###
http://localhost:3100/posts
###
http://localhost:3100/posts/wall/@JewPaltz
###
http://localhost:3100/posts/feed/@JewPaltz
###
POST http://localhost:3100/posts/reset



###
http://localhost:3100/activities
###
http://localhost:3100/activities/@vp
###
POST http://localhost:3100/activities/reset

###
POST http://localhost:3100/activities/add
Content-Type: application/json

    { 
        "handle": "@vp",
        "date": "2021-11-22",
        "activities": { "name": "running", "info": "10 miles", "time": 20 }
    }