http://localhost:3100/users
###
http://localhost:3100/users/61a3bcb38549a368d6422371
###
POST http://localhost:3100/users/reset
###
POST http://localhost:3100/users/login
Content-Type: application/json

    { 
        "handle": "@test",
        "password": "a"
    }
###
PATCH http://localhost:3100/users/pic/61a3b8cb45d05f502827b6ec
Content-Type: application/json

    {
        "pic": "https://pic.onlinewebfonts.com/svg/img_28608.png"
    }



###
POST http://localhost:3100/users/friends/@test
###
POST http://localhost:3100/users/friends/add/@test/@JewPaltz
###
DELETE http://localhost:3100/users/friends/remove/@test/@JewPaltz
###
http://localhost:3100/users/friends/find/p



###
http://localhost:3100/posts
###
http://localhost:3100/posts/wall/@JewPaltz
###
http://localhost:3100/posts/feed/@test
###
POST http://localhost:3100/posts/reset



###
http://localhost:3100/activities
###
http://localhost:3100/activities/@test
###
POST http://localhost:3100/activities/reset