http://localhost:3100/users
###
http://localhost:3100/users/61953d517d480cd4282aab1b
###
POST http://localhost:3100/users/reset
###
POST http://localhost:3100/users/login
Content-Type: application/json

    { 
        "handle": "@vp",
        "password": "Her"
    }
###
POST http://localhost:3100/users/friends/@vp

###
POST http://localhost:3100/users/follow/@vp/@JewPaltz

###
DELETE http://localhost:3100/users/unfollow/@vp/@JewPaltz


###
http://localhost:3100/posts
###
http://localhost:3100/posts/wall/@JewPaltz
###
http://localhost:3100/posts/feed/@JewPaltz
###
POST http://localhost:3100/posts/reset



###
http://localhost:3100/activities
###
http://localhost:3100/activities/@vp
###
POST http://localhost:3100/activities/reset